# Generated by Django 3.1.7 on 2021-03-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(max_length=255, upload_to='')),
                ('bg', models.ImageField(max_length=255, upload_to='')),
                ('profile', models.ImageField(max_length=255, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='skype',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
